src/App/Modulos/Vendas/Controllers/GestaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Modulos.Vendas.Controllers
{
    [Area("Vendas")]
    [Route("gestao-vendas")]
    public class GestaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("detalhe-pedido/{id:int}")]
        public IActionResult Detalhes(int id)
        {
            return View("Index");
        }
    }
}

src/App/Modulos/Vendas/Views/Gestao/Index.cshtml
<h2>Gestão de Vendas!</h2>

src/App/Modulos/Vendas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - AppSemTemplate</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestao Vendas</a>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Vendas" asp-controller="Gestao" asp-action="Detalhes" asp-route-id="1">Teste Pedido</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>Seu site ASP.NET feito do jeito certo!!</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/cep.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>